services:
  app:
    build: .
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/docker #dossier avec le fichier qu'on recupere

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres 